---
title: "Assignment 8: R notebooks and gapminder w/ggplot -- Recreate the outcomes of Greg Martin's R video"
output: html_notebook
---

```{r install and load_gapminder}
install.packages("gapminder")  # if already have installed, don't need to re-install
library(gapminder)             # load the package by using library() function

```

```{r get data frame}
data(gapminder)
```

```{r summary}
summary(gapminder)            # obtain a summary of each of the variables in the data frame
```

```{r mean() function}
mean(gapminder$gdpPercap)     # mean(data$variable)
```

```{r sign a value}
x <- mean(gapminder$gdpPercap)   # create new object by signing them with "<-" sign
x
```

```{r attach() function}
attach(gapminder)  # then you can just simply refer to the variable without having the name of the data frame and $ sign
```

```{r median}
median(pop)       # instead of median(gapminder$pop)
```

```{r histogram_lifeExp}
hist(lifeExp)     # make a histogram for life expectancy
```

```{r histogram_pop}
hist(pop)         # make a histogram for population, but ugly...
```

```{r histogram_log}
hist(log(pop))    # do a log transformation
```

```{r boxplot}
boxplot(lifeExp ~ continent)
```

```{r plot}
plot(lifeExp ~ gdpPercap)
```

```{r plot_log}
plot(lifeExp ~ log(gdpPercap))

```

```{r install and load_dplyr}
#install and  load "dplyr"
install.packages("dplyr")
library(dplyr)
```

```{r filter_and_select}
# focus on a subset of the rows: filter out particular countries
gapminder %>%
  select(country, lifeExp) %>%
  filter(country == "South Africa" |
           country == "Ireland") %>%
  # set the criteria: South Africa or Ireland
  group_by(country) %>%
  # aggregate data by two countries
  summarise(Average_life = mean(lifeExp)) # create a summary value for the average
```

```{r T test}
# make a new data frame called df1
df1 <- gapminder %>%
  select(country, lifeExp) %>%
  filter(country == "South Africa" |
           country == "Ireland")

## T test: compare the average life expectancy in the two contries 
t.test(data = df1, lifeExp ~ country)
```

```{r install and load_ggplot2}
#install and  load "ggplot2"
install.packages("ggplot2")
library(ggplot2)
```

```{r ggplot}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=gdpPercap, y= lifeExp)) +
  geom_point()
```

```{r ggplot_color}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=gdpPercap, y= lifeExp, col=continent)) +  # color by continents
  geom_point()
```

```{r ggplot_transparent}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=gdpPercap, y= lifeExp, col=continent)) +
  geom_point(alpha = 0.5)    # make a little transparent by using alpha
```

```{r ggplot_dot size}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=gdpPercap, y= lifeExp, col=continent, size=pop)) +
  # make the size of dots proportional to the size of the population
  geom_point(alpha = 0.5)   
```

```{r ggplot_log}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=log(gdpPercap), y= lifeExp, col=continent, size=pop)) +
  # do a log transformation to the GDP per capital, that makes the data more linear
  geom_point(alpha = 0.5)
```

```{r ggplot_geom_smooth}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=log(gdpPercap), y= lifeExp, col=continent, size=pop)) +
  geom_point(alpha = 0.5) +
  geom_smooth()  # put lines to track the various continents by using geom_smooth
```

```{r ggplot_facet}
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=log(gdpPercap), y= lifeExp, col=continent, size=pop)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm) +
  # make it into a linear model by setting method
  facet_wrap(~continent) # divide out the various continents into separate facets by facet_wrap
```

```{r ggplot_color for year}
# now we don't need to use color to distinguish them
# instead, we can use color to represent different years
gapminder %>%
  filter(gdpPercap < 50000) %>%
  ggplot(aes(x=log(gdpPercap), y= lifeExp, col=year, size=pop)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm) +
  facet_wrap(~continent)
```

```{r linear model}
lm(lifeExp ~ gdpPercap)   # lm excutes linear model
```

```{r linear model_summary}
summary(lm(lifeExp ~ gdpPercap))   # make a summary to get details
```

```{r linear model_multivariate analysis}
summary(lm(lifeExp ~ gdpPercap+pop))   # do multivariate analysis
```

